import 'inter-ui';
import React from 'react';
import ReactDOM from 'react-dom';
// @ts-ignore
import { BrowserRouter } from 'react-router-dom';
import { App } from './App';
import './index.css'; // generated by tailwindcss
import * as serviceWorker from './serviceWorker';

ReactDOM.render(
  <BrowserRouter>
    <App />
  </BrowserRouter>,
  document.getElementById('root')
);

serviceWorker.register();
